name = "TimeTracking 🕰️"
description = "Track and analyze your project-/work-times easialy across multiple devices  with this webxdc app."
source_code_url = "https://github.com/webxdc/timetracking-webxdc"
