name: Create .xdc Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.2
      with:
        node-version: 18
    - name: build .xdc file
      id: build
      run: |
        yarn
        yarn build
    - uses: ncipollo/release-action@v1
      with:
        artifacts: dist-zip/*.xdc
